version: '3.8'

services:
  desktop-app:
    build:
      context: .
      dockerfile: desktop-app/Dockerfile
    expose:
      - '3000'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  discord-bot:
    build:
      context: .
      dockerfile: discord-bot/Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped 