version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - '3001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3 